# Generated by Django 5.2.7 on 2025-11-01 03:20

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('query_type', models.CharField(choices=[('radius', 'Radius Search'), ('bbox', 'Bounding Box'), ('polygon', 'Polygon'), ('corridor', 'Corridor')], max_length=50)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=100, unique=True)),
                ('route_short_name', models.CharField(max_length=50)),
                ('route_long_name', models.CharField(max_length=255)),
                ('route_type', models.CharField(choices=[('0', 'Tram'), ('1', 'Subway'), ('2', 'Rail'), ('3', 'Bus'), ('4', 'Ferry')], max_length=50)),
                ('operator', models.CharField(blank=True, max_length=100)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['route_short_name'],
                'indexes': [models.Index(fields=['route_id'], name='transport_a_route_i_4d1d10_idx'), models.Index(fields=['operator'], name='transport_a_operato_15a172_idx')],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(max_length=100, unique=True)),
                ('stop_code', models.CharField(blank=True, max_length=50)),
                ('stop_name', models.CharField(max_length=255)),
                ('stop_desc', models.TextField(blank=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('stop_type', models.CharField(choices=[('station', 'Station'), ('stop', 'Stop'), ('terminal', 'Terminal')], default='stop', max_length=50)),
                ('wheelchair_boarding', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['stop_name'],
                'indexes': [models.Index(fields=['stop_id'], name='transport_a_stop_id_875e38_idx'), models.Index(fields=['stop_name'], name='transport_a_stop_na_c739c8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=100, unique=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('bearing', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('occupancy', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_transit', 'In Transit'), ('stopped', 'Stopped'), ('delayed', 'Delayed'), ('off_route', 'Off Route')], default='in_transit', max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='transport_api.route')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['vehicle_id'], name='transport_a_vehicle_831151_idx'), models.Index(fields=['route'], name='transport_a_route_i_d66d19_idx'), models.Index(fields=['-timestamp'], name='transport_a_timesta_11ce29_idx')],
            },
        ),
    ]
