# Generated by Django 5.2.7 on 2025-11-01 04:09

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_id', models.CharField(max_length=100, unique=True)),
                ('agency_name', models.CharField(max_length=255)),
                ('agency_url', models.URLField(blank=True)),
                ('agency_timezone', models.CharField(blank=True, max_length=50)),
                ('agency_lang', models.CharField(blank=True, max_length=10)),
                ('agency_phone', models.CharField(blank=True, max_length=50)),
                ('agency_fare_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Agencies',
                'ordering': ['agency_name'],
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=100, unique=True)),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Calendars',
                'ordering': ['service_id'],
            },
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_id', models.CharField(max_length=100)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('sequence', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['shape_id', 'sequence'],
                'indexes': [models.Index(fields=['shape_id'], name='transport_a_shape_i_826809_idx')],
                'unique_together': {('shape_id', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=100)),
                ('trip_id', models.CharField(max_length=100, unique=True)),
                ('trip_headsign', models.CharField(blank=True, max_length=255)),
                ('direction_id', models.IntegerField(choices=[(0, 'One direction'), (1, 'Opposite direction')], default=0)),
                ('shape_id', models.CharField(blank=True, max_length=100)),
                ('wheelchair_accessible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='transport_api.route')),
            ],
            options={
                'ordering': ['trip_id'],
            },
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_sequence', models.IntegerField()),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('stop_headsign', models.CharField(blank=True, max_length=255)),
                ('pickup_type', models.IntegerField(choices=[(0, 'Regular'), (1, 'No pickup'), (2, 'Phone agency'), (3, 'Coordinate with driver')], default=0)),
                ('drop_off_type', models.IntegerField(choices=[(0, 'Regular'), (1, 'No drop-off'), (2, 'Phone agency'), (3, 'Coordinate with driver')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_times', to='transport_api.stop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_times', to='transport_api.trip')),
            ],
            options={
                'ordering': ['trip', 'stop_sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['trip_id'], name='transport_a_trip_id_6c0e65_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['route'], name='transport_a_route_i_b0293c_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['service_id'], name='transport_a_service_5de6a4_idx'),
        ),
        migrations.AddIndex(
            model_name='stoptime',
            index=models.Index(fields=['trip'], name='transport_a_trip_id_4827ab_idx'),
        ),
        migrations.AddIndex(
            model_name='stoptime',
            index=models.Index(fields=['stop'], name='transport_a_stop_id_ab9b6a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stoptime',
            unique_together={('trip', 'stop_sequence')},
        ),
    ]
